import Head from 'next/head';
import HomeDisplaySection from '../components/organisms/HomeDisplaySection';
import styles from '../styles/Home.module.css';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Twitch | Clone</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/twitch-favicon.png' />
            </Head>

            <div className={styles.carousel_wrapper}>
                <h1>video carousel goes here</h1>
            </div>

            <div className={styles.main_content}>
                <section>
                    <HomeDisplaySection
                        linkText={'Live channels'}
                        headerText={`we think you'll like`}
                        showMore
                    />
                </section>
                <section>
                    <HomeDisplaySection
                        linkText={'Categories'}
                        headerText={`we think you'll like`}
                    />
                </section>
                <section>
                    <HomeDisplaySection headerText={`What's hot`} showMore />
                </section>
                <section>
                    <HomeDisplaySection
                        headerText={`Recently Released Games`}
                        showMore
                    />
                </section>
                <section>
                    <HomeDisplaySection
                        headerText={`Recently Released Games`}
                        showMore
                    />
                </section>
            </div>
        </div>
    );
}
