import Head from 'next/head';
import HoverableText from '../components/atoms/HoverableText';
import HomeDisplaySection from '../components/organisms/HomeDisplaySection';
import styles from '../styles/Home.module.css';
import categoryData from '../assets/data/channel-categories.json';
// import liveStreamsData from '../assets/data/live-streams.json';

// export const getStaticPaths = async () => {
//     const res = await fetch('https://jsonplaceholder.typicode.com/users');
//     const data = await res.json();

//     const paths = data.map((user) => {
//         return {
//             params: {
//                 id: user.id.toString(),
//             },
//         };
//     });

//     return {
//         paths: paths,
//         fallback: false,
//     };
// };

export const getStaticProps = async (context) => {
    const res = await fetch(`http://localhost:3000/all-streams`);
    const data = await res.json();

    return {
        props: {
            data: data,
        },
    };
};

export default function Home({ data }) {
    console.log(data);

    return (
        <div className={styles.container}>
            <Head>
                <title>Twitch | Clone</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/twitch-favicon.png' />
            </Head>

            <div className={styles.carousel_wrapper}>
                <h1>video carousel goes here</h1>
            </div>

            <div className={styles.main_content}>
                <section>
                    <HomeDisplaySection
                        contentData={data}
                        perLine={3}
                        type={'stream'}
                        headerText={
                            <div className={styles.section_header}>
                                <HoverableText
                                    text={'Live channels'}
                                    fontSize={'18px'}
                                    fontWeight={'bold'}
                                    hoverEffects={{
                                        changeColor: true,
                                        addUnderline: true,
                                    }}
                                    initialColor={'#bf94ff'}
                                    hoverColor={'#a970ff'}
                                    handleOnClick={() => {}}
                                />
                                <div
                                    className={styles.pad_left}
                                >{`we think you'll like`}</div>
                            </div>
                        }
                        showMore
                    />
                </section>
                <section>
                    <HomeDisplaySection
                        contentData={categoryData}
                        perLine={6}
                        type={'game'}
                        headerText={
                            <div className={styles.section_header}>
                                <HoverableText
                                    text={'Categories'}
                                    fontSize={'18px'}
                                    fontWeight={'bold'}
                                    hoverEffects={{
                                        changeColor: true,
                                        addUnderline: true,
                                    }}
                                    initialColor={'#bf94ff'}
                                    hoverColor={'#a970ff'}
                                    handleOnClick={() => {}}
                                />
                                <div
                                    className={styles.pad_left}
                                >{`we think you'll like`}</div>
                            </div>
                        }
                    />
                </section>
                <section>
                    <HomeDisplaySection
                        headerText={
                            <div className={styles.section_header}>
                                <div>{`What's hot`}</div>
                            </div>
                        }
                        showMore
                    />
                </section>
                <section>
                    <HomeDisplaySection
                        contentData={categoryData}
                        perLine={6}
                        type={'game'}
                        headerText={
                            <div className={styles.section_header}>
                                <div>{`Recently Released Games`}</div>
                            </div>
                        }
                    />
                </section>
                <section>
                    <HomeDisplaySection
                        headerText={
                            <div className={styles.section_header}>
                                <div>{`Recently Released Games`}</div>
                            </div>
                        }
                        showMore
                    />
                </section>
                <section>
                    <HomeDisplaySection
                        headerText={
                            <div className={styles.section_header}>
                                <div
                                    className={styles.pad_right}
                                >{`Recommended`}</div>
                                <HoverableText
                                    text={'League of Legends'}
                                    fontSize={'18px'}
                                    fontWeight={'bold'}
                                    hoverEffects={{
                                        changeColor: true,
                                        addUnderline: true,
                                    }}
                                    initialColor={'#bf94ff'}
                                    hoverColor={'#a970ff'}
                                    handleOnClick={() => {}}
                                />
                                <div
                                    className={styles.pad_left}
                                >{`channels`}</div>
                            </div>
                        }
                        showMore
                    />
                </section>
            </div>
        </div>
    );
}
